events {
worker_connections 1024;
}
http {
upstream backend {
server backend:3000;
}
server {
    listen 80;

    location / {
        return 200 '<html><body><h1>TechRetail - Tienda Online</h1><p>Plataforma de comercio electronico peruano</p></body></html>';
        add_header Content-Type text/html;
    }

    location /api {
        proxy_pass http://backend;
    }
}
}
